apiVersion: v1
kind: Service
metadata:
  name: test-deploy-openshift
  labels:
    app: test-deploy-openshift
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

  selector:
    app: test-deploy-openshift
  type: ClusterIP
  sessionAffinity: None
